name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build -c Release
      working-directory: CustomHelper/CustomHelper

    - name: Test
      run: dotnet test
      working-directory: CustomHelper/CustomHelper

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Determine version
      id: version
      run: echo "::set-output name=package_version::1.0.$((BUILD_ID++))"
      
    - name: Build
      run: |
        dotnet build -c Release
        dotnet pack -c Release /p:PackageVersion=${{ steps.version.outputs.package_version }}
      working-directory: CustomHelper/CustomHelper/
       
    - name: Publish to GitHub Packages
      run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/Ghost-Sound/index.json --api-key ${{ secrets.API_NUGET_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
